#!/bin/sh

success () {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning () {
    echo "$(tput setaf 1)$1$(tput sgr0)"
}

newline () {
    echo ""
}

echo "Flotilla Firmware Updater"

if [ ! -f "./firmware/flotilla-dock.hex" ] || [ ! -L "./firmware/flotilla-dock.hex" ]; then
    warning "No flotilla-dock.hex found. Exiting!"
    exit 0
fi

newline
warning "This update will break compatibility with older versions of flotillad"
warning "and change your Dock's serial baud rate to 115200"
warning "Press CTRL+C now if you're not sure, otherwise... enjoy!"
newline
read -rsp $'Press any key to continue...\n' -n1 key
newline
warning "Please unplug your Flotilla Dock if it is plugged in!"
newline

sudo sleep 2

success "Plug in your Flotilla Dock now."
read -rsp $'Press any key to continue...\n' -n1 key
newline

sudo ./firmware/dfu-programmer atxmega32a4u erase
sudo ./firmware/dfu-programmer atxmega32a4u flash ./firmware/flotilla-dock.hex

success "Update finished, enjoy!"
warning "Please unplug/replug your Flotilla Dock before use!"

exit 0
