#!/bin/bash

success () {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning () {
    echo "$(tput setaf 1)$1$(tput sgr0)"
}

newline () {
    echo ""
}

echo "Flotilla Firmware Updater"

if [ ! -f "./stable/flotilla-dock.hex" ]; then
    warning "No flotilla-dock.hex found. Exiting!"
    exit 0
fi

newline
warning "This update will reset your Dock's serial baud rate to 9600"
newline

read -rsp $'Press any key to continue...\n' -n1 key

newline
warning "Please unplug your Flotilla Dock if it is plugged in!"

newline
sudo sleep 2
success "Plug in your Flotilla Dock now then"
read -rsp $'Press any key to continue...\n' -n1 key
newline

sudo ./dfu-programmer atxmega32a4u erase
sudo ./dfu-programmer atxmega32a4u flash ./stable/flotilla-dock.hex
sudo ./dfu-programmer atxmega32a4u launch

success "Update finished, enjoy!"
