#!/bin/bash

if [ -f /etc/init.d/flotillad ]; then
    echo -e "Stopping Flotilla Deamon...\n"
    sudo service flotillad stop
fi

echo -e "Launching Flotilla pre-release...\n"

./flotillad/flotilla-armhf -d &

if [ "$DISPLAY" ]; then
    cd ./rockpool
    python ./rockpool.py
fi

exit 0
