#!/bin/bash

pkgdeplist=( "libboost-system1.55.0" "libboost-filesystem1.55.0" "libboost-program-options1.55.0" "libboost-date-time1.55.0" )

apt_pkg_req () {
    APT_CHK=$(dpkg-query -W --showformat='${Status}\n' $1|grep "install ok installed")

    if [ "" == "$APT_CHK" ]; then
        true
    else
        false
    fi
}

if [ $(id -u) -ne 0 ]; then
    echo -e "Install must be run as root. Try 'sudo ./install'\n"
    exit 1
fi

updatedb=false

for pkgdep in ${pkgdeplist[@]}
    do if apt_pkg_req "$pkgdep" ; then
        updatedb=true
    fi
    done

if $updatedb ; then
    echo -e "Updating package indexes..."
    sudo apt-get update
fi

for pkgdep in ${pkgdeplist[@]}
    do echo -e "Checking for dependencies..."
    if apt_pkg_req "$pkgdep" ; then
        sudo apt-get --yes --force-yes install "$pkgdep"
    fi
done

if [ -d /usr/lib/x86_64-linux-gnu ]; then
    if [ -f /usr/lib/x86_64-linux-gnu/libserialport.so.0.0.0 ]; then
        echo -e "libserialport already installed. Updating..."
    fi
    cp ./dependencies/libs-amd64/libserialport* /usr/lib/x86_64-linux-gnu/

    if [ ! -f /usr/lib/x86_64-linux-gnu/libserialport.so.0 ]; then
        ln -s /usr/lib/x86_64-linux-gnu/libserialport.so.0.0.0 /usr/lib/x86_64-linux-gnu/libserialport.so.0
    fi

    if [ ! -f /usr/lib/x86_64-linux-gnu/libserialport.so ]; then
        ln -s /usr/lib/x86_64-linux-gnu/libserialport.so.0.0.0 /usr/lib/x86_64-linux-gnu/libserialport.so
    fi
    chown root:staff /usr/lib/x86_64-linux-gnu/libserialport*
else
    if [ -f /usr/local/lib/libserialport.so.0.0.0 ]; then
        echo -e "libserialport already installed. Updating..."
    fi
    cp ./dependencies/libs-i386/libserialport* /usr/local/lib/

    if [ ! -f /usr/local/lib/libserialport.so.0 ]; then
        ln -s /usr/local/lib/libserialport.so.0.0.0 /usr/local/lib/libserialport.so.0
    fi

    if [ ! -f /usr/local/lib/libserialport.so ]; then
        ln -s /usr/local/lib/libserialport.so.0.0.0 /usr/local/lib/libserialport.so
    fi
    chown root:staff /usr/local/lib/libserialport*
fi

ldconfig

echo -e "All done!\n"

exit 0
