#!/bin/bash

if getent group dialout | grep $(whoami); then
    echo "current user is part of dialout group"
else
    echo "adding current user to dialout group"
    sudo adduser $(whoami) dialout
    echo "you need to log out then log back in for changes"
    echo "to take effect (then run this script again)"
    exit 1
fi

if [ -f /etc/init.d/flotillad ]; then
    echo -e "Stopping Flotilla Deamon...\n"
    sudo service flotillad stop
fi

echo -e "Launching Flotilla pre-release...\n"

if [-d /usr/lib/x86_64-linux-gnu ]; then
    exec ./flotillad/flotilla-amd64 -d &
else
    exec ./flotillad/flotilla-i386 -d &
fi

if [ "$DISPLAY" ]; then
    cd ./rockpool
    python ./rockpool.py
fi

exit 0
