#!/bin/sh

success() {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning() {
    echo "$(tput setaf 1)$1$(tput sgr0)"
}

newline() {
    echo ""
}

echo "Flotilla Firmware Updater"

if [ -f "./firmware/flotilla-dock.hex" ] || [ -L "./firmware/flotilla-dock.hex" ]; then
    success "dock firmware file found"
else
    warning "No flotilla-dock.hex found. Exiting!"
    exit 0
fi

newline
warning "This update will break compatibility with older versions of flotillad"
warning "and change your Dock's serial baud rate to 115200"
warning "Press CTRL+C now if you're not sure, otherwise... enjoy!"
newline
read -rsp $'Press any key to continue...\n' -n1 key
newline

RESULT=$(lsusb -d 16d0:08c3)

if [ ! -z "$RESULT" ]; then
    warning "Please unplug your Flotilla Dock!"
    while [ ! -z "$RESULT" ]; do
        RESULT=$(lsusb -d 16d0:08c3)
        sleep 0.01
    done
fi

success "Plug in your Flotilla Dock now."
success "Updating should continue automatically."
newline

while ! lsusb -d 03eb:2fe4; do
    sleep 0.01
done

sleep 0.2

if [ -d /usr/lib/x86_64-linux-gnu ]; then
    sudo ./firmware/dfu-programmer-amd64 atxmega32a4u erase
    sudo ./firmware/dfu-programmer-amd64 atxmega32a4u flash ./firmware/flotilla-dock.hex
else
    sudo ./firmware/dfu-programmer-i386 atxmega32a4u erase
    sudo ./firmware/dfu-programmer-i386 atxmega32a4u flash ./firmware/flotilla-dock.hex
fi

success "Update finished, enjoy!"
warning "Please unplug/replug your Flotilla Dock before use!"

exit 0
